### ISSUE TITLE
Failure to build using cuda 12.2

### ISSUE THREAD

**Issue by jvesely** [inducer/pycuda#420]
```
      src/wrapper/wrap_cudadrv.cpp: In function ‘void init_module__driver()’:
      src/wrapper/wrap_cudadrv.cpp:1034:26: error: ‘CU_TARGET_COMPUTE_20’ was not declared in this scope; did you mean ‘CU_TARGET_COMPUTE_90’?
       1034 |     .value("COMPUTE_20", CU_TARGET_COMPUTE_20)
            |                          ^~~~~~~~~~~~~~~~~~~~
            |                          CU_TARGET_COMPUTE_90
      src/wrapper/wrap_cudadrv.cpp:1037:26: error: ‘CU_TARGET_COMPUTE_21’ was not declared in this scope; did you mean ‘CU_TARGET_COMPUTE_61’?
       1037 |     .value("COMPUTE_21", CU_TARGET_COMPUTE_21)
            |                          ^~~~~~~~~~~~~~~~~~~~
```

1. install cuda toolkit 12.2
2. pip install pycuda

**Expected behavior**
pycuda builds and installs built wheel

**Environment (please complete the following information):**
 - OS: linux
 - CUDA version: 12.2
 - CUDA driver version: 535.54.03
  - PyCUDA version: 2022.1
  - Python version: 3.7

**Comment by jvesely** [comment]
pycuda 2022.2 + requires Python 3.8, so I guess 3.7 is out of luck

**Comment by inducer** [comment]
You can probably just reset the corresponding line in `setup.py`, I don't think any 3.8 features are actually required.

**Comment by jvesely** [comment]
> You can probably just reset the corresponding line in `setup.py`, I don't think any 3.8 features are actually required.

thank you, that worked.
